### ISSUE TITLE
[Feature request] Code block annotations

### ISSUE THREAD

**Issue by adrhill** [tlienart/Franklin.jl#1048]
The [Modern Julia Workflows](https://modernjuliaworkflows.github.io) blog switches between shell, code and REPL code blocks quite frequently. It would be nice to be able to annotate code blocks to avoid confusing readers.

**Example of this feature in a blog post:**
https://fasterthanli.me/series/advent-of-code-2022/part-1

**Mock-up illustrating the problem:**
<img width="567" alt="Screenshot 2023-08-16 at 00 20 26" src="https://github.com/tlienart/Franklin.jl/assets/20258504/460487d1-80f5-4037-8551-a49c0851a34f">
<img width="567" alt="Screenshot 2023-08-16 at 00 20 41" src="https://github.com/tlienart/Franklin.jl/assets/20258504/6062a498-a727-4ba3-9402-c070a7c93ec1">

CC @gdalle

**Comment by tlienart** [comment]
I've not looked into it yet but you should be able to do precisely the same kind of stuff as in the blog post; shell repl and code blocks have separate classes and so a different style can be applied to those.

Have you tried copying whatever it is that they're doing for the styling of their code blocks on the rust blog post and see if it works for you?

**Comment by adrhill** [comment]
I'm not well versed in web technologies, but I got something that works halfway using `.hljs::before`:

```css
.hljs::before {
  content: attr(class);
  position: absolute;
  top: 0;
  right: 0;
  padding: 0.2rem 0.5rem;
  background-color: #1d2735;
  border-bottom-left-radius:10px;
  font-size: 0.75rem;
  font-weight: 700;
  text-transform: uppercase;
}
```

<img width="534" alt="image" src="https://github.com/tlienart/Franklin.jl/assets/20258504/f9cc1b33-75f8-4280-a17c-282032cbe99b">

Since the `class` attribute doesn't exactly correspond to the language name, `LANGUAGE-JULIA HLJS` is printed.

Reading the highlightjs docs, it looks like access to the `data-language` attribute is easy to obtain:
https://highlightjs.readthedocs.io/en/latest/plugin-recipes.html#data-language

How can I make use of this in Franklin?

**Comment by adrhill** [comment]
I've also noticed a bug where using Franklin's live REPL evaluation, docstring headers are identified as Ruby code:
<img width="556" alt="image" src="https://github.com/tlienart/Franklin.jl/assets/20258504/4fa24e16-8312-49f6-9f37-ea9a611b264e">

**Comment by tlienart** [comment]
ok so I was under the impression that there was one additional class, not just the `language-julia-repl` for REPL, Shell and Help mode; will change that.

**Comment by tlienart** [comment]
would you mind testing #1050 which should hopefully help you for your use case?

**Comment by adrhill** [comment]
In the following example, #1050 turns the class from `language-julia-repl hljs` to `language-julia-repl julia-repl-help hljs`.

<img width="592" alt="image" src="https://github.com/tlienart/Franklin.jl/assets/20258504/20ab333c-0ccf-40b3-a163-e4a95754e704">

The code block inside the doc string is wrongly still shown as `hljs language-ruby`.

How can I include https://highlightjs.readthedocs.io/en/latest/plugin-recipes.html#data-language in Franklin? This should allow me to turn e.g. `language-bash hljs` to `Bash` and `language-julia hljs` to `Julia`.

**Comment by tlienart** [comment]
(sorry for not answering your points properly in the first shot)

so the custom classes should allow you to add specific styling *only* to the dedicated class, let me play with it a bit so I can see whether I can modify what you did to get something that might be more satisfactory

for the ruby stuff what happens is that the `help` path in Franklin takes the help result from Julia and just "places" it there, and that stuff has code blocks which are not indicated (i.e. naked triple backquotes as opposed to ones with `julia`). This is then seen by highlight.js which, when it doesn't get an indication of what the language is, tries to infer what it is. And here it gets to ruby.

next steps are:

(1) let me play with the CSS stuff for the annotation thing, I'll get back to you here if I can make something nicer work
(2) see if we can make code blocks in the help mode be annotated so that highlight knows it's julia, I'll try to extend #1050 to that effect. There may be corner cases where examples in docstrings are actually not Julia code but I imagine it's going to be seldom so for now it's probably fine.

**Comment by adrhill** [comment]
Thanks a lot!

**Comment by adrhill** [comment]
The lastest commit of #1050 works really well already!

However, sing something like 
```css
.julia-repl::before {
  content: "Julia REPL";
}
```
seems to currently remove the whitespace after the `help?>` and `julia>` prompts in code. I'm not sure where this is coming from.

<img width="592" alt="image" src="https://github.com/tlienart/Franklin.jl/assets/20258504/2a81e7b6-f582-4a5b-b37d-1c1cb67f7895">

**Comment by tlienart** [comment]
hmm this is odd, Franklin definitely adds a space. Could you:

1. in the browser dev console, highlight one of those code blocks and copy paste the entire corresponding HTML here so we can check that there's a space (there should be) and what classes have been added
1. paste here the entirety of the CSS that has `pre` `code` `hljs` and `.julia-repl` associated with it so I can try to reproduce the issue and play with it
1. tell me how exactly you're loading highlight.js whether it's a bundled script or whether it's your own version tweaked to find these `julia>`, `shell>` and `pkg>` and what code you entered to do that

**Comment by tlienart** [comment]
ok, there's some stuff I don't understand (why that space got swallowed), I suspect it's due to the `julia>` being selected into a single span *without* the space after it, then the code being inserted afterwards and the code getting lost in it. I think it's the javascript that removes this but I did not dig into it.

In any case the following will fix the problem:

```css
.hljs .prompt_::after {
content: " ";
}
```

the `prompt_` class is used for the `julia>` ,`shell>`, `help?>` etc elements, so here we're just forcing a space to be added after it. 

**Note**: I didn't check but let's say you only had the problem with `julia-repl` then you'd just do `.julia-repl .prompt_::after{ ...}` etc.

hope this works! I'll merge the modifications in #1050 which seem to do what you were hoping for.

**Comment by gdalle** [comment]
@adrhill can you transfer this to our new Xranklin version?

**Comment by adrhill** [comment]
Sure, let me try. 👍

**Comment by adrhill** [comment]
For reference, this is used in https://github.com/modernjuliaworkflows/modernjuliaworkflows.github.io/pull/67.
___

Some insights since then:

The weird `julia>Julia` prompt in https://github.com/tlienart/Franklin.jl/issues/1048#issuecomment-1684142414 stems from the fact that `language-julia-repl` contains other `language-julia` blocks. These trigger `::before` from the language tags, printing `"Julia"` again:
```css
.language-julia::before {content: "Julia";}
```

<img width="432" alt="image" src="https://github.com/tlienart/Franklin.jl/assets/20258504/8b3a7a30-2a7d-40d8-b9e5-f51f4b1029b9">

All in all, the approach with `::before` works, but I'm not sure its the best solution.
The language tags end up inside the HLJS `<code>` element, making them scroll with the code.
It would also be nice to combine them with a "copy code" button on hover.

Some discussion on this topic can be found in https://github.com/highlightjs/highlight.js/issues/1108#issuecomment-608415953, but I'm not familiar enough with JS and its DOM to really understand it.

I also noticed that Xranklin doesn't have the distinction between `julia-repl` and other REPL modes like `julia-repl-pkg`, `julia-repl-help` and `julia-repl-shell` that was introduced to Franklin in #1050.
