### ISSUE TITLE
Demos page leads to 404

### ISSUE THREAD

**Issue by mitiemann** [tlienart/Franklin.jl#1077]
On the [Franklin website](https://franklinjl.org/), trying to click on the [demos](https://franklinjl.org/demos/) page leads to a 404.

**Comment by tlienart** [comment]
Hey @mitiemann, yes thanks, I'll fix that this week

**Comment by diegozea** [comment]
I was going to report the same. I found the problem with this line: https://github.com/tlienart/Franklin.jl/blob/8c043252f61e0a6217fd9c873a5be66cac5a8f3a/docs/index.md?plain=1#L26C1-L26C149

**Comment by mkitti** [comment]
I also just encountered this issue: https://franklinjl.org/demos/ (404)

**Comment by mkitti** [comment]
The issue seems to be a missing index.html in https://github.com/tlienart/Franklin.jl/tree/gh-pages/demos

Several of the links do work within demos:
* https://franklinjl.org/demos/foo/
* https://franklinjl.org/demos/mathjax/
* https://franklinjl.org/demos/weave/
* https://franklinjl.org/demos/wgl/ (errors printed)

**Comment by fkastner** [comment]
The `index.html` seems to be missing since #1066 was merged. Maybe some codeblock now throws an error and didn't before?

**Comment by tlienart** [comment]
Hello guys, this is now fixed (https://franklinjl.org/demos/), sorry am struggling a bit with my maintainers' duty atm
