### ISSUE TITLE
Slow preview on macOS (Safari)

### ISSUE THREAD

**Issue by cormullion** [tlienart/Franklin.jl#400]
Something I meant to mention later was that I sometimes see problems running the preview locally using macOS Safari. I end up using Firefox instead.

Basically what happens is that after starting `serve()` in the terminal, the website loads from `http://localhost:8000/` but it loads quite slowly. - and sometimes times out. 

I did a bit of playing with the Safari Developer tools, and got things like this:

<img width="1515" alt="Screenshot 2020-03-14 at 12 45 50" src="https://user-images.githubusercontent.com/52289/76682178-c67fa800-65f1-11ea-87a3-23229952504e.png">

where it's complaining that it can't find `franklin.css`, although it's there and OK.

Run it again, and this time it might complain that it can't find `http://localhost:8000/libs/bootstrap/bootstrap.min.css` or one of the other files:

<img width="1517" alt="Screenshot 2020-03-14 at 13 03 23" src="https://user-images.githubusercontent.com/52289/76682443-3727c400-65f4-11ea-9115-0a92771ff43a.png">

On Firefox, every page loads almost instantly. So I don't think there's anything going on here that is caused by Franklin code. Possibly there are some issues with LiveServer or HTTP that would be beyond my investigative powers. But in case anyone has problems with rendering local sites on Safari, this issue might provide some confirmation.

macOS 10.14.5 (Mojave), Safari 12.1.1, Julia 1.4, Franklin v0.6.8

**Comment by tlienart** [comment]
Hmm thanks for this report and sorry about that; I generally use Firefox because I'm used to the developer tools but I sometimes use Safari and Chromium as well and did not encounter problems. I actually just tried now and the page (julialang) loaded instantly; I'm on the same version of Safari but I'm still on Sierra (yeah I couldn't be bothered to upgrade...). 

Do you experience similar issues with your own website?

And indeed, I think the issue is much more likely to come from LiveServer than Franklin.

**Comment by tlienart** [comment]
@cormullion any news on this? are you still experimenting problems?

**Comment by cormullion** [comment]
I'll do a few updates and see what happens. (Haven't had any inspiration for writing anything recently...😂)

**Comment by cormullion** [comment]
Well I'm now on macOS 10.15.4 Catalina, Franklin v0.7.1, Safari 13.1, and there are no slowdowns that I can find. Sometimes upgrades are really upgrades?!
