### ISSUE TITLE
Variable scope leaking

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#412]
```
$ cat index.html 
{{ isdef title }}
    <h1>{{ fill title }}</h1>
{{ end }}

$ cat post.md 
@def title = "Title in post.md"

$ cat config.md 
@def title = "Title in config.md"

$ cat __site/index.html 
<h1>Title in post.md</h1>       <---  ???
```

**Comment by tlienart** [comment]
Thanks, the expected behaviour is `Title in config` (always); I'm assuming that you're seeing sometimes one sometimes the other? this is because when processing `*.html` files  the dictionary of local variables they have access  to is not set properly; this is a simple issue to fix;  thanks for reporting!

**Comment by fredrikekre** [comment]
Yea, it is a bit random which one shows up.
