### ISSUE TITLE
Footnote becomes H2

### ISSUE THREAD

**Issue by fredrikekre** [tlienart/Franklin.jl#432]
Happens if you have one and only one empty line after a footnote before a `---` divider:
```
julia> println(Franklin.fd2html("""
       hello[^a]

       [^a]: world

       ---
       """))
<p>hello<sup id="fnref:a"><a href="#fndef:a" class="fnref">[1]</a></sup>
<h2><table class="fndef" id="fndef:a">
    <tr>
        <td class="fndef-backref"><a href="#fnref:a">[1]</a></td>
        <td class="fndef-content">world</td>
    </tr>
</table>
</h2>
```

**Comment by tlienart** [comment]
:eyes: ok... I believe this is because of the following:

```
julia> Markdown.parse("""
       a
       ---
       """
       )
  a
  ===
```

I think that's in some Markdown spec that something "underlined" by `---` or maybe `===` becomes a title. The footnote side is irrelevant here:

```julia
julia> s
"a\n---\n"

julia> s |> fd2html
"<h2>a</h2>\n"
```

The easy way out would be to take `---` as a token and replace it with `<hr>` ourselves.

Thanks for the report!

**Comment by fredrikekre** [comment]
> I think that's in some Markdown spec that something "underlined" by --- or maybe === becomes a title.

Yes, but then it needs to be the line below, can't be empty lines as in my example. It is correct when there is no empty line, i.e. your example:
```
julia> "a\n---" |> fd2html
"<h2>a</h2>\n"
```
is correct, and without the footnote it is also correct:
```
julia> "a\n\n---" |> fd2html
"<p>a</p>\n<hr />\n"
```
