### ISSUE TITLE
Please support chronological list of recent post and taxonomic lists of posts

### ISSUE THREAD

**Issue by newptcai** [tlienart/Franklin.jl#479]
For a blog, a chronological list of recent posts is essential.

As for taxonomy of posts, Pelican supports both tags and categories. Each post can belong to only one category, but multiple tags. This is quite useful for a blog with many posts.  See Pelican document here

https://docs.getpelican.com/en/stable/content.html#file-metadata

**Comment by tlienart** [comment]
So actually the chronological list can already be done with current code, I just need to show how, the answer to #449 shows how to show a list of pages, and you can write julia code that gets evaluated at build time to get the list of recent posts meeting given requirements. Granted this is not trivial if you’re new to Franklin and I’m planning to add a clear example in the docs and the templates.

Tags are WIP and should be in soon. It’s taking me a bit of time because I tried to rush it in before around 0.7.5 and it backfired due to issues with page variable scopes. I now have a plan for that, just need to implement and test it :-)

Once the tag machinery is in, the category stuff would essentially be the same I would think and could be customised by users.

**Comment by tlienart** [comment]
Wrt chronological list of content, a more complete case is applied for the JuliaLang blog posts:

* result: https://julialang.org/blog/
* this  is generated by calling a function `{{blogposts}}` 
* that function is spec'ed here: https://github.com/JuliaLang/www.julialang.org/blob/4c998de90c1e39c8d2e62a1f5a41e34f524872ad/utils.jl#L27-L58

This doesn't replace a complete, documented example but you can see the gist where you collect the blog pages using Julia code and then you write some stuff that uses that list which is then  parsed by Franklin.

**Comment by tlienart** [comment]
Ok so  both tags and chronological posts are supported so closing
