### ISSUE TITLE
\begin{align} does not work (but \begin{aligned} does)

### ISSUE THREAD

**Issue by schneiderfelipe** [tlienart/Franklin.jl#624]
Hi. I just found out that KaTeX doesn't support the `align` environment, although it supports `aligned` for the same purpose (see, e.g., KaTeX/KaTeX#1007). I discovered it by trying to reproduce an [example from the manual](https://franklinjl.org/syntax/markdown/#aligned_maths).

This difference between `align` and `aligned` seems to have been discussed in another issue (#403, regarding MathJax support; see [this comment](https://github.com/tlienart/Franklin.jl/issues/403#issuecomment-599740264) by @RoyiAvital about `aligned`).

While I don't advocate for swapping MathJax and KaTeX, as I actually prefer KaTeX due to performance (although supporting both would be great), I think that example in the manual would benefit from a comment on this.

**Comment by tlienart** [comment]
Hello!

Thanks for chipping in. I need a bit of clarification what doesn't work?

* is it using align in Franklin which throws an error? (It shouldn't)
* is it using aligned in Franklin which throws an error? (It should)
* is it that you don't think it's a good idea to convert align in aligned (which is what Franklin does)? If so why not?

I got quite confused on #403 yes I understand that **align** is not supported **in katex** but in Franklin if you use **align** it will be converted for katex to **aligned** and as per the comment there, there's no difference.

I may be missing something though, would you mind listing exactly what you would like and screenshots of differences if any? Thanks!

**Comment by schneiderfelipe** [comment]
> Hello!
> 
> Thanks for chipping in. I need a bit of clarification what doesn't work?
> 
>     * is it using align in Franklin which throws an error? (It shouldn't)
> 
>     * is it using aligned in Franklin which throws an error? (It should)
> 
>     * is it that you don't think it's a good idea to convert align in aligned (which is what Franklin does)? If so why not?

Ok, now I understand! My explanation was confusing because I didn't realize Franklin attempts to convert `align` to `aligned` (I missed that part, sorry)! As such, I am reporting a case where the conversion fails.

> I got quite confused on #403 yes I understand that **align** is not supported **in katex** but in Franklin if you use **align** it will be converted for katex to **aligned** and as per the comment there, there's no difference.

Sure, the conversion is quite reasonable.

> I may be missing something though, would you mind listing exactly what you would like and screenshots of differences if any? Thanks!

## Example

The following piece of code

```
## Preliminaries

Starting with three-dimensional cartesian Gaussian functions,

$$\begin{aligned}
    G_{ijk} (\vec{r}, \alpha, \vec{A}) &= x_A^i y_A^j z_A^k \exp(-\alpha r_A^2) \\
        &= G_i (x, \alpha, A_x) G_j (y, \alpha, A_y) G_k (z, \alpha, A_z)
\end{aligned}$$

with orbital exponent $\alpha$, electronic coordinate $\vec{r}$, nuclear
coordinate $\vec{A}$ (such that $\vec{r}_A = \vec{r} - \vec{A}$), and $i$, $j$
and $k$ as angular quantum numbers (e.g., $i = j = k = 0$ is an s-type orbital,
$i = j = 0$ and $k = 1$ denotes a p-type orbital, etc.). Furthermore, the
one-dimensional Gaussian functions are defined like

$$G_i (x, \alpha, A_x) = (x - A_x)^i \exp(-\alpha (x - A_x) ^ 2)$$

Let's get to the integrals.
```

gives the following screenshot:

![Captura de tela de 2020-09-25 11-18-27](https://user-images.githubusercontent.com/37125/94278399-2223da00-ff21-11ea-9e94-c60d81f2caee.png)

This means `aligned` is passing through (should it?). But if I change the first equation to use `align`,

```
[...]
$$\begin{align}
    G_{ijk} (\vec{r}, \alpha, \vec{A}) &= x_A^i y_A^j z_A^k \exp(-\alpha r_A^2) \\
        &= G_i (x, \alpha, A_x) G_j (y, \alpha, A_y) G_k (z, \alpha, A_z)
\end{align}$$
[...]
```

I get the following

![Captura de tela de 2020-09-25 11-22-19](https://user-images.githubusercontent.com/37125/94278624-6f07b080-ff21-11ea-9015-877432481e77.png)

That is, the `align` to `aligned` conversion failed.

### Things I tried

- Breaking a line between `$$` and `\begin{...}`/`\end{...}` does not work.
- Removing `align`/`aligned` and all instances of `&`/`\\` generates a correct (not aligned) equation.

## Context

```julia
julia> VERSION
v"1.4.1"

(@v1.4) pkg> status Franklin
Status `~/.julia/environments/v1.4/Project.toml`
  [713c75ef] Franklin v0.9.16

```

**Comment by tlienart** [comment]
AAAAAHHH now I understand, thanks for taking the time! (btw you can update Franklin but that's irrelevant). 

whatever is inside a `$$ ... $$`  gets fed directly to KaTeX so if you give it a `aligned` KaTeX will treat it exactly as such, if you give it a `align` it will fail.

The thing is that Franklin tries to be closer to what you would do in LaTeX, you can write the following:

```
\begin{align}
math
\end{align}
```

**without** the `$$`. In that case what happens is that Franklin sees that and feeds KaTeX effectively with `$$\begin{aligned} ... \end{aligned}$$`. Does that make sense?

**Comment by schneiderfelipe** [comment]
Perfect! No bug then, I actually misinterpreted the manual. Thanks for the feedback and explanation!

**Comment by tlienart** [comment]
Seems it would be worthwhile to add your example in the docs, I'll open a separate issue

**Comment by RoyiAvital** [comment]
This is the exact issue using KaTeX.
What if someone copied his code form StackExchange, then it works the way @schneiderfelipe put it at first?

In many MarkDown editors it will work perfectly as they use MathJaX.
I really think the correct path here is to chose the more feature full solution and use MathJaX. Or at least make it an option.

**Comment by tlienart** [comment]
PRs to help in this regards are welcome. So far you're the only potential user who's asked explicitly for MathJax so while I'm still open to it, it's not high priority for me.

**Comment by RoyiAvital** [comment]
I think this issue speaks for itself as not the only one :-).
I don't want MathJaX because I like it, I want it because it offers compatibility to the way MD is usually written with LaTeX.

This is the case above, someone used the regular way of writing and found it to be not working. It is not a coincident he linked to the issue he linked to.
You do offer a bypass, but why?

I'd do a PR had I known how to do it.
By the way, do you find asking people who give feedback to submit a PR a good way to handle feedback?

**Comment by tlienart** [comment]
I'd rather not get into a flamewar unnecessarily. Summarising my points:

- Franklin aims to support LaTeX-like syntax for maths, and doesn't care particularly about whether that is rendered with KaTeX or with something else, the choice for KaTeX was speed and pre-rendering capacity (which MathJax may now equal)
- The `align` environment in that regard **is supported**, it was a misunderstanding as to how you could use it which I should clarify in the docs; irrelevant of MathJax or KaTex, the intended use is that the user can directly do `\begin{align}...\end{align}` like they would in LaTeX, Franklin will then translate that to whatever is expected by the rendering backend (e.g. KaTeX). In other words the philosophy is that users should be able to copy paste math equations from their LaTeX documents and it should work, if it doesn't then there are two possibilities
  - Franklin can do some pre-processing to translate a user input into something comparable that is supported by the backend
  - It's not supported by the backend even in an approximate way (I can imagine there are such cases but I am not aware of good examples yet)
- A key point of your comments here and in the other discussion is that MathJax supports a wider range of things than KaTeX. I'm ready to believe this but I asked you then and now to give specific examples that people might expect to work from LaTeX, `align` is not one of those as per the point before. I (used to) write a lot of maths using KaTeX and never found it not meeting what I expected from my LaTeX expectation apart from numbering which Franklin handles; thus I am reluctant to prioritise adding support to MathJax when it's unclear what the benefits are.

Your last comment is unnecessary, but yes, if you like a piece of open source software and want something to be supported sooner rather than later, then my opinion is that it's a good thing to try suggest a PR. You'll find that I'm more than willing to help people who might not know where to look in the code base or what to do to.

**Comment by RoyiAvital** [comment]
I think one issue with Open Source world is not being feedback driven because of this approach.
I am a user of a piece of software of yours, do you want the feedback or just PR`s? If just PR's then you are looking for co developers and not for users.

Regarding MathJaX, My main argument is MathJaX allows Copy & Paste experience form existing AMS Math LaTeX code. KaTex may not.
I am just saying it will assist converting more text form PDF generated by LaTeX environment to HTML (Much friendlier to share knowledge) .

You may say it is not of your interest to support this. It's not a design goal of this package. That's a fair decision.
PR or not has nothing to do with it.

Anyhow, I am full of appreciation of this. I must say this is a very small issue compared to how valuable is the package.

**Comment by tlienart** [comment]
I think we're on the same page, and I'm definitely open to feedback (there's still an open issue for MathJax support! #403) I think the part where I was being a bit defensive is how to prioritise this effort. 

> Regarding MathJaX, My main argument is MathJaX allows Copy & Paste experience form existing AMS Math LaTeX code. KaTex may not.

This is also my goal for Franklin. And if it so happens that you do that and get a result that looks shit or otherwise fails, please do open an issue with code + screenshot and we can try to figure out from there how to fix it some way or other. 

When I look at http://texdoc.net/texmf-dist/doc/latex-dev/amsmath/amsldoc.pdf it's clear that _Franklin_ doesn't support the whole thing for instance:

* `\begin{equation*}...`
* `\begin{multiline}...` (not supported in KaTeX btw, same for `multicolumn`) 
* `\begin{gather}...`

this is because I just haven't investigated all the mappings. In some cases it might "just work" to use this within a `$$...$$` environment (in which case it's assumed that the backend takes over, KaTex or otherwise) but that's _not_ mere copy pasting. For instance you can write this:

```
# Some markdown
Etc with _emphasis_ etc

\begin{equation}
\frac{
    \begin{array}[b]{r}
      \left( x_1 x_2 \right)\\
      \times \left( x'_1 x'_2 \right)
    \end{array}
  }{
    \left( y_1y_2y_3y_4 \right)
  }
\end{equation}

Some more markdown. Note that there are no \$ anywhere. 
```

It's **easier** to defer everything to the backend and just tell users that they should systematically drop every math block in a `$$...$$` and then I agree that MathJax will be more 1-1 with AMS in this respect. This is still possible by the way but it is true that in that case you depend more closely on what the backend supports.

**Comment by schneiderfelipe** [comment]
> I think this issue speaks for itself as not the only one :-).
> I don't want MathJaX because I like it, I want it because it offers compatibility to the way MD is usually written with LaTeX.
> 
> This is the case above, someone used the regular way of writing and found it to be not working. It is not a coincident he linked to the issue he linked to.

I'm not advocating MathJax over KaTeX (I actually prefer KaTeX due to its superior performance). Back in the day KaTeX had no support for `mhchem`, which I use a lot, [but that is not the case anymore](https://mhchem.github.io/MathJax-mhchem/). As such, I currently don't have any special need that exclusively requires MathJax. Having support for that would be nice in any case, but that alone wouldn't stop me using KaTeX.

On the other hand, Franklin seems to integrate LaTeX-like commands in ways that are deeper than simple Markdown + math in LaTeX. In that regard, it seems perfectly logical to have environments such as `equation` and `align`. While we're at it, I could suggest three things that could make the experience even more integrated:
- implement a wider set of environments such as `multiline`, etc. (@tlienart already [commented on that above](https://github.com/tlienart/Franklin.jl/issues/624#issuecomment-699514514))
- support the `\newenvironment` tag along with `\newcommand`
- support starred commands (e.g., `\newcommand{\mycommand*}{...}`)

@tlienart If you like the proposals, I could open separate issues for them.

**Comment by tlienart** [comment]
Sounds good to me thanks! Maybe open a separate one for each are some are easier than others (eg newenvironment)?
