### ISSUE TITLE
Raw versus processed text in environments

### ISSUE THREAD

**Issue by epatters** [tlienart/Franklin.jl#659]
I'm excited to use the new environments feature. For example, I currently have a command for inserting [tikz-cd](https://ctan.org/pkg/tikz-cd) figures:

````
\newcommand{\tikzcd}[2]{
```julia:./!#1
#hideall
using TikzCDs
save(SVG(joinpath(@OUTPUT, "!#1.svg")), TikzCD(raw"""!#2"""))
```
\fig{./!#1}
}
````

This command works well but I'd rather it be an environment. When I try

````
\newenvironment{tikzcd}[1]{
```julia:./!#1
#hideall
using TikzCDs
save(SVG(joinpath(@OUTPUT, "!#1.svg")),
     TikzCD(raw"""}{
"""))
```
\fig{./!#1}
}
````

I get errors like 

```
ERROR: Franklin.LxObjError("Command or environment '\\arrow' was used before it was\ndefined.")
```

suggesting that Franklin is now trying to interpret LaTeX macros as Franklin commands. Is there a better way to implement this environment?

**Comment by tlienart** [comment]
Oh wow, I like this spirit! ok so here you do something that's a bit too crazy for Franklin because you split a code environment in two, I know it might seem like a small thing to "join them first then parse" but that's currently not allowed in a simple `\newenvironment`. 

**However** it's easy to achieve what you want with a little bit of Julia. Put this in your `utils.jl`:

```julia
function env_tikzcd(e, _)
  content = strip(Franklin.content(e)) # what's effectively between the begin and the end
  name = strip(e.braces[1]) # what's in the "option" brace
  return """
    ```julia:./!#1
    #hideall
    using TikzCDs
    save(SVG(joinpath(@OUTPUT, "!#1.svg")), TikzCD($content))
    ```
    \fig{./!#1}
    """
end
```

And this would be called with `\begin{tikzcd}{name}tikz code\end{tikzcd}` 

I haven't tried this, you might have to adjust a little bit for instance to escape the `content` string in case Tikz doesn't like it; but that shouldn't be too hard hopefully. Let me know how it goes!

**Comment by epatters** [comment]
Thanks, I didn't know you could define environments in Julia code. This approach works great!

**Comment by tlienart** [comment]
Cool! I imagine you figured that the `#1` needed to be replaced by `$name`, sorry I had typed my answer a bit in a rush.

Glad it works for you, looking forward to seeing the result 😁

**Comment by epatters** [comment]
In case it's helpful to anyone else, here's the final code:

```julia
function env_tikzcd(e, _)
  content = strip(Franklin.content(e))
  name = strip(Franklin.content(e.braces[1]))
  return """
    ```julia:./$name
    #hideall
    using TikzCDs
    save(SVG(joinpath(@OUTPUT, "$name.svg")),
         TikzCD(raw\"\"\"$content\"\"\"))
    ```
    \\fig{./$name}
  """
end
```
