### ISSUE TITLE
Shortcut for code blocks to evaluate & show output

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#683]
Following a suggestion on Slack, it could be nice to offer a shortcut to mean "execute this and show the output directly after"; basically similar to the literate mode. 

A possible syntax could be

````
```julia!
a = 7
print(a)
```
````

which would

1. insert the code block  (unless it's hidden)
2. eval the code block
3. insert the output of the code block

**Comment by jkrumbiegel** [comment]
Yes that sounds very good. My typical mode of working is geared towards writing tutorials and long explanations, so I have a lot of text with occasional code blocks. Usually, these code blocks are also connected, so that the second one depends on the variables created in the first, etc.

This is not very easy to achieve with the current system, as Literate syntax requires # for every ordinary text line, and the code block way needs users to come up with paths to store the code snippets manually.

So if we did a syntax like 
```
```julia!
```

maybe there could be another variant where continuation is possible like

```
```julia!same_block
x = 1
```
Some text
```julia!same_block
y = x + 2
```
```

**Comment by tlienart** [comment]
Ah continuation is already permitted; all code on a page is considered like a script in a module (each page is a module and all code on that page is run within it) you can check  this with

````
```julia:ex1
x = 1
```
and
```julia:ex2
print(x+1)
```
\textoutput{ex2}
````

**Comment by jkrumbiegel** [comment]
Oh then I misunderstood that part of the system, or maybe that was because I went into it with the Documenter mindset, where you have to explicitly continue example blocks

**Comment by tlienart** [comment]
thanks for the  feedback anyway! I'm thinking that we could even allow both these  shortcuts:

````
```julia!
x = 1
```

and even shorter

```!
x = 1
```
````

after all it's not ambiguous, and even if, in a hypothetical future, we could specify which language to use to run the cell, then this could just be set with the `lang` global parameter so it's fine I think :)
