### ISSUE TITLE
(docs) add lunr index compilation in CI

### ISSUE THREAD

**Issue by tlienart** [tlienart/Franklin.jl#754]
at the moment the index is updated only manually

**Comment by lucaferranti** [comment]
I tried to automate the search index generation by the following code patch in the `deploy.yml`.

```
julia -e '
            using Pkg; Pkg.activate("."); Pkg.instantiate();
            using NodeJS; run(`$(npm_cmd()) install highlight.js`);
            run(`$(npm_cmd()) install lunr`);
            run(`$(npm_cmd()) install cheerio`);
            using Franklin; lunr();
            optimize()'
```

However this gave the error
```
+ lunr@2.3.9
added 1 package from 1 contributor and audited 2 packages in 0.388s
found 0 vulnerabilities
npm WARN deprecated cheerio-select-tmp@0.1.1: Use cheerio-select instead
npm WARN saveError ENOENT: no such file or directory, open '/home/runner/work/juliaintervals.github.io/juliaintervals.github.io/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/runner/work/juliaintervals.github.io/juliaintervals.github.io/package.json'
npm WARN juliaintervals.github.io No description
npm WARN juliaintervals.github.io No repository field.
npm WARN juliaintervals.github.io No README data
npm WARN juliaintervals.github.io No license field.
+ cheerio@1.0.0-rc.5
added 14 packages from 4 contributors and audited 16 packages in 0.927s
found 0 vulnerabilities
→ Building the Lunr index...       Could not find folder:  ../../__site
/home/runner/work/juliaintervals.github.io/juliaintervals.github.io/_libs/lunr/build_index.js:89
    for (var i = 0; i < files.length; i++) {
                              ^
TypeError: Cannot read property 'length' of undefined
    at main (/home/runner/work/juliaintervals.github.io/juliaintervals.github.io/_libs/lunr/build_index.js:89:31)
    at Object.<anonymous> (/home/runner/work/juliaintervals.github.io/juliaintervals.github.io/_libs/lunr/build_index.js:103:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
┌ Warning: There was an error building the Lunr index.
└ @ Franklin ~/.julia/packages/Franklin/eCeWy/src/manager/extras.jl:33
```
when I create the search index locally. Everything works fine.

**Comment by tlienart** [comment]
ah this one is tractable, the issue is the `../../__site` (https://github.com/tlienart/Franklin.jl/blob/4a870b9e62f487902696189bcc7b94d61381aa7c/docs/_libs/lunr/build_index.js#L9); it doesn't find that folder. 

So the good thing to try here is to figure out the right path for GitHub and then once that's found we can see how to ensure that it works both locally and on CI 😄

**Comment by lucaferranti** [comment]
swapping the order of `lunr` and `optimize` worked, the index was created successfully, here's the link to the log if you wanna check: https://github.com/JuliaIntervals/juliaintervals.github.io/runs/1813276389 . I guess the issue was that it was trying to create the index from `__site` before the folder existed.

**Comment by lucaferranti** [comment]
On the other side, I still have the problem that I get old results from deleted pages, I think what happens is the following:
1.`optimize()` creates the __site from the source code, using the previous index that I had built locally
2. `lunr()` creates the new index somewhere but not into the `__site` folder, from where the deployment then happens.

I think possible fixes would be:
1. call `optimize` a second time after `lunr` (I guess the codes would not be run again?)
or
2. modify `const OUTPUT_INDEX` to be `../../__site/libs/lunr/lunr_index.js` in this way the index would be built directly into the `__site` folder. I am not sure whether this would work, since I don't know if Franklin does some postprocessing to the index during `optimize`/`serve` or if it merely copies it to `__site`.

I think the second one is maybe easier if it works?

**Comment by tlienart** [comment]
for (1) you could do `serve(single=true); lunr(); optimize()` and no the code will not be run again. I think that's the right way to go. You're correct that lunr needs to have a filled `__site` before it can be hoped to work. 

IMO that's the simplest path.

**Comment by lucaferranti** [comment]
Looks like we have a winner! The following works.
```
   - run: julia -e '
            using Pkg; Pkg.activate("."); Pkg.instantiate();
            using NodeJS; run(`$(npm_cmd()) install highlight.js`);
            run(`$(npm_cmd()) install lunr`);
            run(`$(npm_cmd()) install cheerio`);
            using Franklin; serve(single=true); lunr();
            optimize()'
```
