### ISSUE TITLE
Consider using ./ for base directory in links

### ISSUE THREAD

**Issue by PhilipLoewen** [tlienart/Franklin.jl#763]
Here's the head stanza from the index.html file emitted by Franklin, showing some edits I added later. See below for comments.
```html
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="./libs/katex/katex.min.css">
     
   <link rel="stylesheet" href="./libs/highlight/github.min.css">
   
  <link rel="stylesheet" href="./css/franklin.css">
<link rel="stylesheet" href="./css/pure.css">
<link rel="stylesheet" href="./css/side-menu.css">
<!-- style adjustments -->
<style>
.franklin-content{padding-left:10%;}
@media (min-width: 940px) {
  .franklin-content {width: 640px; margin-left: 0px; padding-left: 80px;}
  .header {width: 700px;}
}
</style>
<link rel="icon" href="./assets/favicon.png">

   <title>Franklin Example</title>  
</head>
```
Basically I did a global search-and-replace to upgrade '`href="/`' to '`href="./`' in 6 places. That made it possible to quit Julia completely and view a properly-presented page by aiming Firefox at the URL "`file:///home/me/mySite/__site/index.html`". Without those dots, Firefox interpreted those paths as absolute locations on my machine. Of course an active web-server knows better, but I think an active web-server would also get this right with the dots in place.

Would it be reasonable to adjust Franklin to insert those dots automatically?

**Comment by tlienart** [comment]
Hello Philip!

So if I understand properly, what you want is to be able to see a locally-built website locally after having terminated your Julia session. You can do this with the following steps:

1. when you're about to "finish" your work locally with Julia still open, call `optimize(minify=false, prerender=false)` (*)
2. navigate to `__site` and use a proper site renderer, note that if you just open with your browser, things will not render properly (this is not due to Franklin, it's because the different files will not be loaded properly by your browser). If you want a standalone app to do this that does not require Julia to be running, consider [browser sync](https://browsersync.io). Running it in the folder `__site` will render the site locally. (**)

(*) the minify / prerender will make it easier to inspect the source HTML if you want, you can also remove these args and just use `optimize()`
(**) note that the package [LiveServer.jl](https://github.com/tlienart/LiveServer.jl) is effectively a simple "browser sync", this is what is called when you use `serve()` in Franklin.

I hope this makes sense.

**Comment by PhilipLoewen** [comment]
Thanks a lot for this amazing response (fast, comprehensive, and generous!).

The phrase "the right general solution" in your PS is critical. This is the reason I proposed a question instead of even calling it a suggestion. My Firefox browser seemed to find and parse the linked JS and CSS files correctly when I adjusted the paths as shown. But, especially if my lucky observation with N=1 is not (completely_accurate & robust & cross_platform), I am quite content with the alternatives you lay out.

Thanks for building this excellent package and sharing it with the rest of us!
