### ISSUE TITLE
Some links have the prepath baked in, this breaks versioned sites with one `stable` version

### ISSUE THREAD

**Issue by jkrumbiegel** [tlienart/Franklin.jl#875]
For example, on this site http://makie.juliaplots.org/stable/tutorials/basic-tutorial/ the link `lines` points to http://makie.juliaplots.org/v0.15.2/examples/plotting_functions/lines/index.html#lines because the actual release is `0.15.2`. But as far as possible, we want to use the `stable` alias (which is a symlink to the most recent version on the top level). So it would be good if all internal links were prepath independent.

**Comment by tlienart** [comment]
Just so I'm on the same page:

if you were to set: https://github.com/JuliaPlots/Makie.jl/blob/0b1db455ab61a4e2dfc18ea11880433043e8e878/docs/makedocs.jl#L28 manually, you could set it such that the result would be `/stable/` right? 

If you do want versions which I can understand, why not 

1. set that such that if the `deploydecision.subfolder` corresponds to the latest tag then it's replaced by `stable` 
2. have a routine that, if the latest tag has changed, does a second Franklin build with a prepath corresponding to the version and copies the content of `__site` to such a folder?

That way you get on the `gh-pages` branch

- `stable`
- `v0.2`
- `v0.1`
- ...

On the Franklin side, the second item could be baked in the first so that you can generate once and get the same output in two folders but maybe first let me know if you think that would solve your issue

**Comment by tlienart** [comment]
What I'm trying to figure out is what needs to be done. My suggestion above (while annoying to implement right now on the user side, this is not really the point) works as far as I'm aware and does exactly the same thing as Documenter in terms of end result; the reason why there isn't a functionality to do so automatically is just that you're the first to ask for "versions" of the website (apart from the preview trick which is a bit different).

So my previous message was just trying to figure out whether something like what I suggest would solve the problem or whether there's something more fundamental to fix with `prepath` as you seemed to suggest in your initial message.

**Comment by jkrumbiegel** [comment]
So in the current build there's a link `<a href="/v0.15.2/examples/plotting_functions/lines/index.html#lines">lines</a>` on the page http://makie.juliaplots.org/stable/tutorials/basic-tutorial/ which should be `<a href="../../examples/plotting_functions/lines/index.html#lines">lines</a>`

**Comment by tlienart** [comment]
I *think* the thing with the prepath is a bit of a distraction in this discussion in that the end effect that I think you want (i.e. get something similar to Documenter) can be achieved with it as it is now anyway i.e.:

* get `/stable/foo/bar/` be identical to `/${LATEST_RELEASE}/foo/bar/` 

so that you can always refer users to `/stable/foo/bar/` 

also adding a banner like Documenter does for `/${NOT_LATEST_RELEASE}/foo/bar/` is fairly easy. 

(I'm saying it's a distraction because I don't think it's a requirement to get the result and I also think it's not as easy as you might think to just use `../..` paths)

**Comment by jkrumbiegel** [comment]
so I understand it correctly that you propose to run every tagged version build twice (means adding a new section in github actions, almost copying the tag workflow but changing only the prepath), once with `vX.X.X` and once with `stable`? It seems a "messy" solution to me somehow because of the duplicated effort (the build takes > 20 minutes) just for this one string change.

**Comment by tlienart** [comment]
right, this is what I suggested you do _right now_ as the functionality to have multiple pre-paths is not yet in Franklin.

But of course, what I'm suggesting as a real solution is that there would be only a single build and then what happens with the "prepath" resolution would just be applied twice (this is precisely what you're saying with the string change and a bunch of files being copied into a dedicated folder)

**Comment by tlienart** [comment]
this is now in https://github.com/tlienart/Franklin.jl/pull/876

I'm trying to build the docs with a fork of Makie.jl https://github.com/tlienart/Makie.jl/actions/runs/1194414987 . 

The syntax from the user perspective is that in the `deploy` (or in your case in the `makedocs`) you'd have

```
optimize(..., version="xxx", ...)
```

where version can be

* `dev` in which case the base will be `/prepath/dev/` 
* `v0.1` in which case the base will be `/prepath/v0.1/` AND `/prepath/stable/` (copy) AND `/prepath/dev/` 

the idea being that when you tag a release you get 3 equivalent URLs (stable, tagged, dev), when you move with untagged you have dev ahead and stable=lasttag, and over time each tagged version stays. I think this is identical behaviour to Documenter

**Todo**, I actually forgot the copy to `/dev/` when `stable` is updated.

**Comment by tlienart** [comment]
I'll do a pass to polish some bits and pieces but the result is:

* https://tlienart.github.io/Makie.jl/stable/
* https://tlienart.github.io/Makie.jl/0.15.2/
* https://tlienart.github.io/Makie.jl/dev/

Note: the first time you'll have to clean up `gh-pages` branch before doing this.

**Comment by tlienart** [comment]
alright this was merged in master and is about to be released, please give it a shot (after scrubbing `gh-pages` if possible). I'll close this issue for now but feel free to re-open if something doesn't work as you expect it to.

**Comment by jkrumbiegel** [comment]
Thank you, I'll have a look soon when I have time again!

**Comment by jkrumbiegel** [comment]
Ok a couple more questions:

How does this work together with the Documenter deployment function that I'm currently using, should I switch to this github action again that your franklin examples use? I think Documenter expects only one folder to copy to.

Why did you advise that I scrub the gh-pages branch? I would prefer not to delete the old versions, I want to implement the version dropdown menu later and still need them for that.

**Comment by tlienart** [comment]
I'm not familiar with the Documenter deployment function but you seemed to be getting from that function a version is that incorrect? so if you receive a version string, then you should pass this as

```
version = deploydecision.subfolder
# + some logic like
if version == "dev" # or if it's not a version, not sure what you get out of deploydecision.subfolder
    optimize(..., version="dev", ...)
else
    optimize(..., version=version, ...)  # for stuff like 0.15.2 
end
```

re scrubbing the `gh-pages` branch it's just that currently the `gh-pages` branch corresponds exactly to the site meaning that on it you have the `index.html` corresponding to the landing page.

But with this version thing you're moving to a folder-based deployment meaning that your site will not be at the root of `gh-pages` but in subfolders of it `gh-pages/stable`, `gh-pages/0.15.2/` etc. 

For the sake of keeping things clean, I'd advise cleaning the `gh-pages` as otherwise your `gh-pages` branch will be a bit messy (not that it matters).

**Comment by jkrumbiegel** [comment]
I don't have the site in the top folder, you can see the structure here https://github.com/JuliaPlots/Makie.jl/tree/gh-pages
There's just an index.html to redirect to `stable`.

Ok so I guess I have to move back to the github deploy action thingy, and treat the site as one folder with `dev`, `stable` and `vX.Y` folders inside it (potentially). That should not be too bad actually. I'll still use the Documenter.jl logic to determine what version I'm actually on, it has a quite handy function for that.

**Comment by jkrumbiegel** [comment]
Oh but then this breaks the preview functionality again.. Documenter has a nice way of handling that, which additionally notifies the pull request on github so one can easily view the preview. What is the way it should work now for previews? I would then not set the version keyword and do this via the prepath again?

I still feel that being able to just move Franklin generated sites to any subfolder of any site I want would be beneficial. The root issue of that is still the relative vs absolute paths..

**Comment by tlienart** [comment]
the preview functionality would be the exact same but just pushing to `gh-preview` instead of `gh-pages` and with `version="PRNumber"` with a conditional a bit like this one:

https://github.com/JuliaLang/www.julialang.org/blob/d067ed286b7fe4a901728c880e4f9735ef10682a/.github/workflows/deploy.yml#L71-L86

**Comment by tlienart** [comment]
the `../` stuff is annoying because for internal links the user has to think about where the page is with respect to the root, if they then move the page to another folder, all their links on that page are potentially broken.

> I still feel that being able to just move Franklin generated sites to any subfolder of any site I want would be beneficial.

this is effectively the case though, you can pass anything you want to `version` though anything else than `dev` will assume it's actually a version name and will update `stable` and `dev` accordingly; this might not be desirable and we could replace it with logic that expects a String that starts with `v` and otherwise just dumps the content in that folder. Alternatively we could add a path where the version passed is `preview_$PR_NUMBER`, and if that's the case, not update `dev` and `stable`.

**Comment by jkrumbiegel** [comment]
Ok I see, well we don't really write any absolute links ourselves, they are all generated by `reflink` or something like that. So I didn't think about usability for those cases.

**Comment by jkrumbiegel** [comment]
With a `gh-preview` branch I can't access it without an external thing like netlify, right? I kind of prefer the Documenter way of doing this, it has fewer moving parts. I'm thinking how hard it would be to read the site folder after generating it and rewriting all absolute links to relative ones.

**Comment by tlienart** [comment]
ah yes that's correct, give me a few minutes and I'll show a demo with a `previews/` folder same as Documenter (I just want to add logic that when you set that, it doesn't overwrite `stable/`.

**Comment by tlienart** [comment]
alright you can see the result here: 

https://github.com/tlienart/franklinversions/tree/gh-pages

**Comment by tlienart** [comment]
here is the deploy line https://github.com/tlienart/franklinversions/blob/dd0495cf940cb113ce29eaeb04e026785a36c0bf/.github/workflows/Deploy.yml#L32 which you'd collect from some other logic like GitHub actions or whatever
