### ISSUE TITLE
Check if a variable is default with `isempty`

### ISSUE THREAD

**Issue by chunjiw** [tlienart/Franklin.jl#883]
`{{ isempty var }}` checks whether `var` is either nothing or actually empty, but it complains if `var` exists but not iterable (e.g. default value in some cases). It would be better if it returns `true` if `var` is default value, since the user didn't define it explicitly.

**Comment by chunjiw** [comment]
My current solution on `date` is to define it as an empty string `@def date = ""`, so it is not rendered in the final html file.

**Comment by tlienart** [comment]
Nice! so I understand what you're suggesting (check if it's the default) but this might get tricky in some cases where if the value is default, it's actually fine (e.g. if you explicitly want a string to be empty), so I think there's two paths:

1. have a way to check if a value is something like `{{ifequal var value}}`
2. update `{{isempty var}}` to check if a date is not `0001-01-01` 

(1) will come eventually but is a bit tricky because we need to parse `value` and make sure it's evaluated in a sensible sandbox (e.g. a place with `Dates`); I think it will be done eventually.

(2) is super easy and would already solve your problem we just need to change this line:

https://github.com/tlienart/Franklin.jl/blob/7fddc7910157e3c4e24d8825267e15aa756bd006/src/converter/html/blocks.jl#L71

which, in any case, is probably a bit dodgy. So maybe we could replace it by

```
_isempty(v)
```

and define

```julia
_isempty(v) = false
_isempty(::Nothing) = true
_isempty(v::AbstractArray) = isempty(v)
_isempty(v::AbstractString) = isempty(v)
_isempty(v::Date) = (v == Date(1,1,1))
```

would you like to try a PR with something like this?

**Comment by tlienart** [comment]
ok actually I've added the change :)

**Comment by chunjiw** [comment]
Thank you! It is well explained :) Your code is much better than what I have in mind :)
