### ISSUE TITLE
0.10.57 and 0.10.58 broke the Julia Computing website

### ISSUE THREAD

**Issue by ViralBShah** [tlienart/Franklin.jl#891]
The blog section of our website did not compile correctly on both these versions. Just noting here to see if others have faced the same problem.

**Comment by tlienart** [comment]
Thanks and sorry! I'll have a look

**Comment by tlienart** [comment]
Ok here's the analysis:

- blogpost pages at the end have `{{recentblogposts}}` this function calls `pagevar` to retrieve variables (like title, date) from other pages
- at the initial pass, not all pages are seen, so `pagevar(some_path)` will trigger a conversion of the page `some_path`
- since you have `{{recentblogposts}}` also on `some_path`, it does itself trigger `pagevar` and the order of operations means that this will cycle to stack overflow

I've now added a safety mechanism to avoid this happens; in a future version of Franklin this won't be needed.

### Notes on the JC blog

- It's not ideal to add the `{{recentblogposts}}` on every blog page, this should be part of the layout. I'll try to fix this and suggest the changes in a PR. 
- there's a bunch of other small errors with page variables that I'll also try to fix along the way

**Comment by ViralBShah** [comment]
Thank you!
