### ISSUE TITLE
Maybe allow html in markdown without fences?

### ISSUE THREAD

**Issue by schlichtanders** [tlienart/Franklin.jl#920]
Other markdown I've been using allows to place html right into markdown.

Having the possibility to easily switch back to markdown within some html div would be awesome as well.

One big advantage of going with such standard is that syntax highlighting can be borrowed from other markdown linters.
Having custom latex-commands is nice and handy, however they fall short in some cases with syntax highlighting and autocompletion.

Was there a particular reason why html is only allowed within `~~~`  blocks?

**Comment by fredrikekre** [comment]
Probably because the Markdown stdlib doesn't support it: https://github.com/JuliaLang/julia/issues/17837

**Comment by fredrikekre** [comment]
Even CommonMark.jl have special syntax for it: https://github.com/MichaelHatherly/CommonMark.jl#raw-content

**Comment by tlienart** [comment]
So this is actually an easy one: there's no way I will do it; you could criticise the initial decision but it was a choice from very early on to have the MD and the HTML fully separated which simplifies a lot of stuff. And @fredrikekre is right that Base.Markdown doesn't support it but even if it did I'd have done the same.

Another one that I kind of had supported but will definitely not be supported in the future is indented code blocks. 

Blocking these two allows to (much more easily) handle custom parsing rules for things like latex-like commands or hfuns which is by design. 

--- 

## One side note

I'd be fully ready to acknowledge that it's not always a good idea to reinvent the wheel that some people thought about markdown for a while and that lacing HTML into the markdown and/or having indented code blocks is cool. So in the next version there will be the possibility to basically switch off Franklin's parser in favour of another one (typically CommonMark's) and then you can do whatever you want in there that is compatible with that parser **but** you won't be able to use any of Franklin's goodies. That should make it nice for people who want to migrate sites and don't want to have to bother with adjusting old pages so they're Franklin-compliant.

**Comment by tlienart** [comment]
Ah and yes I agree for the syntax hl... we'd have at some point to define custom rules for "Franklin markdown" that could be a good project 🤪

**Comment by schlichtanders** [comment]
thank you all for your input.
very valuable and appreciated
