### ISSUE TITLE
html script misses new lines on gitlab pages

### ISSUE THREAD

**Issue by schlichtanders** [tlienart/Franklin.jl#921]
this is mainly for reporting purposes, I am not sure why this happens, but it happens while using Franklin, so may be related.

I have a javascript script in my html layout template file and it does not work sometimes (sometimes it surprisingly works) and it seems one reason is that it gets compressed into a single line.

However I use line comments, and hence the whole script breaks when newlines are deleted.

Possible Workaround: Try block comments

**Comment by tlienart** [comment]
Could you try switching off the minification in case you were using it? (`optimize(minify=false)`)

**Comment by schlichtanders** [comment]
thank you for your help. I haven't activated the minifcation. Probably this is a default in the gitlab cicd. Can you help me pointing to the right place where I need to change things?

**Comment by schlichtanders** [comment]
if minify is doing such big mistakes, it looks crucially buggy to me.

What do you think about disabling it by default? And add a warning note to the documentation of the minify option.

**Comment by schlichtanders** [comment]
Found it (there is exactly one call to `optimize`):
```
image: julia:1.6

before_script:
  - apt-get -qq update; apt-get -y install git python3-dev python3-pip
  - pip3 install css-html-js-minify
    
pages:
  stage: deploy
  script:
    - julia --project=@. -e 'import Pkg; Pkg.instantiate();
      using NodeJS; run(`$(npm_cmd()) install highlight.js`);
      using Franklin;
      optimize(minify=false)'
    - mv __site public
  artifacts:
    paths:
      - public
  only:
    - main
```

**Comment by tlienart** [comment]
yes I'm aware this minification is less than ideal, also it's actually not Franklin, it's a Python script that does the job (https://github.com/tlienart/Franklin.jl/blob/master/src/scripts/minify.py -- https://github.com/juancarlospaco/css-html-js-minify).

The reason this was baked in was because it's very simple and _generally_ doesn't break sites (whereas more powerful minifiers require a lot more care). However minifying when you use GitLab or GitHub is essentially useless (they serve the site compressed anyway). 

And yes minification will disappear in the next version, leaving it up to the user to call their preferred minifier (or none at all).
