### ISSUE TITLE
Footnote <table>s are nested in a <p> tag

### ISSUE THREAD

**Issue by McSinyx** [tlienart/Franklin.jl#936]
Semantically `<p>` tags should not contain `<table>`.

**Comment by tlienart** [comment]
There's quite a few issues opened here to do with `<p>` tags. Long story short Franklin is something on top of the `Base.Markdown` markdown to html conversion which is faulty. Franklin then bends over backwards to try to avoid having unclosed `<p>` blocks (which it doesn't always manage to do). 

The future version which can be previewed here https://github.com/tlienart/Xranklin.jl (though not recommended for use atm, it's work ongoing) has its own markdown to HTML converter; it's not perfect but it's better by avoiding going through the Base converter. 

Note also that while I've put a fair bit of effort into trying to limit the number of cases where tags are unclosed (because it's important for things like minifiers), this is not something that's trivial to do for a number of reasons and in order not to have complicated and hard to maintain logic in the code, there will definitely be cases where the generated HTML will be properly rendered by any standard browser and yet won't be fully semantically correct.

Hope that makes sense!

**Comment by McSinyx** [comment]
That's OK, I've already came up with a work around specifically for the footnotes.
