### ISSUE TITLE
Quadruple backticks are parsed incorrectly

### ISSUE THREAD

**Issue by jkrumbiegel** [tlienart/Franklin.jl#938]
On this page you can see that there is one dangling backtick in every Julia code block https://jkrumbiegel.com/pages/2021-12-28-new-features-dataframemacros/

This seems to be because Literate.jl generates quadruple instead of triple backticks, which should work nonetheless I think.

**Comment by tlienart** [comment]
This is a change in Literate.jl (https://github.com/fredrikekre/Literate.jl/blob/v2.9.4/CHANGELOG.md#changed) which went from 3 to 4 backticks. 

It's a bit annoying to change that in Franklin because users of older versions of Literate.jl will have their code fail. 

To make thing simple, for now I'd recommend going with pinning Literate to 2.8 and I'll try to see if we can add some logic that checks which version of Literate is currently in place, if it's above 2.8 we should have

`````julia
const LITERATE_JULIA_FENCE   = "````$LITERATE_FENCER"

# and later

config=Dict("codefence" => (LITERATE_JULIA_FENCE => "````")),
`````

cc @fredrikekre who might have better ideas for how to deal with this

**Comment by tlienart** [comment]
@jkrumbiegel could you kindly test this on the latest patch release? I added support for Literate's FranklinFlavor and adjusted a few things with the case of quadruple backticks. I believe it should fix your issue with the trailing backtick.
